spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootapp
    username: postgres
    password: 2087
    driver-class-name: org.postgresql.Driver
 
# HIBERNATE (HibernateProperties)
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: create